apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - imageName: hello-helm
deploy:
  helm:
    releases:
    - name: hello-helm
      chartPath: hello-helm-chart
      namespace: default
      values:
        image: hello-helm
      setValues:
        service.type: NodePort
        service.nodeport: 30000
