apiVersion: v1
kind: Service
metadata:
  name: hello-helm
  labels:
    app: {{ template "hello-helm-chart.name" . }}
    chart: {{ template "hello-helm-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
      protocol: TCP
      {{if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodeport)))}}
      nodePort: {{.Values.service.nodeport}}
      {{end}}
  selector:
    app: {{ template "hello-helm-chart.name" . }}
    release: {{ .Release.Name }}
